FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=Brycecoin/Brycecoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY Brycecoin.tar.gz /Brycecoin.tar.gz
RUN tar -xvf /Brycecoin.tar.gz

#ADD . /Brycecoin
RUN cd /Brycecoin/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /Brycecoin && scripts/windows-crosscompile/compile-Brycecoin.sh
